start-at-login = true

# auto-tile into columns
after-login-command = []
after-startup-command = [
  'exec-and-forget borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0',
]

on-window-detected = [
  { if = 'test %{app-name} ~= gneiss', run = 'move-node-to-workspace 2' },
]

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# new windows tile to the right
default-root-container-layout = 'tiles'
default-root-container-orientation = 'horizontal'

# mouse follows focus
on-focus-changed = ['move-mouse window-lazy-center']

# gaps
[gaps]
inner.horizontal = 8
inner.vertical = 8
outer.left = 8
outer.right = 8
outer.top = 8
outer.bottom = 8

[mode.main.binding]
ctrl-left = 'focus left'
ctrl-right = 'focus right'
ctrl-shift-left = 'move left'
ctrl-shift-right = 'move right'

# Caps layer signals: H/J/K/L, with Shift for movement
f17 = 'focus --boundaries all-monitors-outer-frame left'
f18 = 'workspace next'
f19 = 'workspace prev'
f20 = 'focus --boundaries all-monitors-outer-frame right'
shift-f17 = 'move --boundaries all-monitors-outer-frame left'
shift-f18 = ['move-node-to-workspace next', 'workspace next']
shift-f19 = ['move-node-to-workspace prev', 'workspace prev']
shift-f20 = 'move --boundaries all-monitors-outer-frame right'

alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'

alt-shift-1 = ['move-node-to-workspace 1', 'workspace 1']
alt-shift-2 = ['move-node-to-workspace 2', 'workspace 2']
alt-shift-3 = ['move-node-to-workspace 3', 'workspace 3']
alt-shift-4 = ['move-node-to-workspace 4', 'workspace 4']
alt-shift-5 = ['move-node-to-workspace 5', 'workspace 5']
alt-shift-6 = ['move-node-to-workspace 6', 'workspace 6']
alt-shift-7 = ['move-node-to-workspace 7', 'workspace 7']
alt-shift-8 = ['move-node-to-workspace 8', 'workspace 8']
alt-shift-9 = ['move-node-to-workspace 9', 'workspace 9']

# workspace switching (PopOS style)
ctrl-up = 'workspace prev'
ctrl-down = 'workspace next'
# move window between workspaces and follow
ctrl-shift-up = ['move-node-to-workspace prev', 'workspace prev']
ctrl-shift-down = ['move-node-to-workspace next', 'workspace next']

alt-shift-t = 'layout tiles accordion'
alt-shift-f = 'layout floating tiling'
alt-tab = 'workspace-back-and-forth'

ctrl-m = 'fullscreen'
ctrl-backslash = 'macos-native-minimize'
