typeset -U path PATH
path=(${path:#/nix/*})
path=(${path:#${HOME}/.nix-profile/*})
path=(
  "$HOME/.local/bin"
  "$HOME/.local/share/bun/bin"
  "$HOME/.local/share/deno/bin"
  "$HOME/.cargo/bin"
  $path
)
export PATH

export XDG_BIN_HOME="$HOME/.local/bin"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"
