# Generated by nixos-generate-config, then customized.
{ config, lib, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-42518c6f-02b1-4755-be91-75aef3be40ca";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-42518c6f-02b1-4755-be91-75aef3be40ca".device = "/dev/disk/by-uuid/42518c6f-02b1-4755-be91-75aef3be40ca";
  boot.initrd.luks.devices."luks-f8e136e5-0fd2-46e1-9bdf-0c5b428b02b0".device = "/dev/disk/by-uuid/f8e136e5-0fd2-46e1-9bdf-0c5b428b02b0";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/D159-F343";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-f8e136e5-0fd2-46e1-9bdf-0c5b428b02b0"; }
    ];

  # NVIDIA hybrid graphics bus IDs
  hardware.nvidia.prime.intelBusId = "PCI:0:2:0";
  hardware.nvidia.prime.nvidiaBusId = "PCI:1:0:0";

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
